#!/bin/bash
# init.sh - Development environment startup script
# Generated by Long-Running Agent Framework

set -e

echo "🚀 Starting development environment..."

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo "📦 Installing dependencies..."
    npm install
fi

# Check if .env exists
if [ ! -f ".env" ]; then
    echo "⚠️  No .env file found, copying from .env.example..."
    if [ -f ".env.example" ]; then
        cp .env.example .env
    fi
fi

# Start development server
echo "🔧 Starting development server..."
npm run dev &

# Wait for server to be ready
sleep 5

# Health check
if curl -s http://localhost:3000 > /dev/null 2>&1; then
    echo "✅ Development server running at http://localhost:3000"
else
    echo "⏳ Server may still be starting... check http://localhost:3000"
fi

echo ""
echo "📋 Quick Commands:"
echo "   View logs:    npm run dev"
echo "   Run tests:    npm test"
echo "   Build:        npm run build"
echo ""
